name: Enhancement
description: Suggesting new enhancements for the template
labels: ["enhancement"]
body:
  - type: textarea
    id: enhancement_details
    validations:
      required: true
    attributes:
      label: 可改进的内容
      description: 请描述一下可改进的部分。
      placeholder: |
        例如“模板代码中使用了某某功能，但使用另一种功能更好”。
  - type: textarea
    id: code_and_steps
    attributes:
      label: 代码与步骤
      description: 如果可能的话请附上相关代码，或简要描述改进步骤。
  - type: textarea
    id: expected_results
    attributes:
      label: 预期结果
      description: 如果可能的话请附上一份修改后的预期结果，如截图或命令行输出等。
